### ISSUE TITLE
Mutator threads hang

### ISSUE THREAD

**Issue by tianleq** [mmtk/mmtk-openjdk#117]
When a mutator tries to allocate memory, it might trigger a gc and the mutator will end up calling ```mmtk_block_for_gc``` in ```mmtkUpcalls.cpp```. Internally, ```mmtk_start_the_world_count``` is used to indicate each round of gc and mutators relies on its value to know which gc to wait for. The issue resides in ```MutexLocker locker(MMTkHeap::heap()->gc_lock());```.  A thread tries to acquire the gc_lock(), but the VM has already started safepoint synchronization, then the thread will block and once it resumes, it will wait on a non-existing round of gc and hangs forever.

**Comment by k-sareen** [comment]
Maybe we can do something similar to what OpenJDK does here [1], that is, temporarily transition to the `_thread_in_vm` state so that the mutator doesn't get blocked on the lock. It might work (unless I've misunderstood the comment and above issue). 

\[1]: https://github.com/mmtk/openjdk/blob/ca90b43f0f51d9ddf754e6ab134c5030cf54118b/src/hotspot/share/runtime/safepoint.cpp#L841-L843
