### ISSUE TITLE
`MMTK_THREADS` is ignored after #229

### ISSUE THREAD

**Issue by caizixian** [mmtk/mmtk-openjdk#242]

**Comment by wks** [comment]
This topic was discussed in https://github.com/mmtk/mmtk-core/issues/636, and this issue is an instance of it.

The desired order to apply options is

MMTK defaults -> OpenJDK defaults -> environment variables -> command line options

But in https://github.com/mmtk/mmtk-openjdk/pull/229, OpenJDK's default threads setting is applied after the BUILDER instance is (lazily) created, and the environment variables are applied when creating the MMTKBuilder instance.

To fix https://github.com/mmtk/mmtk-core/issues/636, we should allow `Options` instances to created without reading from environment variables, and allow the VMs to choose when to read options from env vars, or not to read from env vars at all.
