### ISSUE TITLE
Throw `OutOfMemory` instead of panicking

### ISSUE THREAD

**Issue by caizixian** [mmtk/mmtk-openjdk#78]
Currently, the OpenJDK binding doesn't override the `out_of_memory` implementation in `Collection`, so when running with extremely small heap size, the VM will panic in Rust instead of throwing a Java exception `OutOfMemory`.

This was done properly in the JikesRVM binding https://github.com/mmtk/mmtk-jikesrvm/blob/8cbdfd6/mmtk/src/collection.rs#L59

**Comment by k-sareen** [comment]
So there is a mismatch between what MMTk expects and what OpenJDK expects to occur on an OOM error.

#### OpenJDK
OpenJDK checks for OOM every (slowpath) allocation [1, 2]. If the object was successfully allocated, it verifies the allocation etc [1]. If the VM is OOM, then a pending exception bit is set for the current thread [2] and the `null` pointer is passed through to the calling Java thread [1]. Here, the Java thread will then check the pending exception bit and then throw the corresponding exception, in this case, it will throw the `OutOfMemoryError`. (One can confirm that it is the Java thread that is throwing the exception instead of the VM as a breakpoint on `print_stack_trace` [3] is not triggered for the `OutOfMemoryError`).

Hence, **OpenJDK allows for allocations to fail (due to OOM) and `null` pointers be passed to Java thread(s)**.

\[1]: https://github.com/mmtk/openjdk/blob/jdk-11.0.11+6-mmtk/src/hotspot/share/gc/shared/memAllocator.cpp#L83
\[2]: https://github.com/mmtk/openjdk/blob/jdk-11.0.11+6-mmtk/src/hotspot/share/gc/shared/memAllocator.cpp#L115-L145
\[3]: https://github.com/mmtk/openjdk/blob/jdk-11.0.11+6-mmtk/src/hotspot/share/classfile/javaClasses.cpp#L2251

#### MMTk
MMTk checks for OOM every (slowpath) allocation [4] as well. However, MMTk handles the OOM case differently. As per the `out_of_memory()` function in `Collection` [5], MMTk expects that an OOM error is thrown immediately. In fact both the binding and the core have many assumptions that MMTk will never return a `null` to the VM for example [6] and [7] to name a few (**Note:** I haven't done a complete audit of the binding and core for this assumption). Naively returning `null` to the VM at an OOM error breaks underlying assumptions of how MMTk works.

Hence, **MMTk's contract with the VM expects the VM to crash the moment an OOM is reported**.

The OOM implementation on `master` simply panics in Rust when the VM is OOM. This does not break MMTk's expectations, but breaks the VM's expectations. My implementation of OOM will report an OOM error to the VM and then throw the OOM exception. However, this is broken since it only works in a `release` build due to the assertions and checks being disabled (not to mention does not work for `MarkSweep` and `MarkCompact` which are _correctly_ stuck in an infinite loop of OOM reporting to the VM).

\[4]: https://github.com/mmtk/mmtk-core/blob/4851e7ac7e8a7bd70ce65935c4ac1ff430cab6f1/src/util/alloc/allocator.rs#L216-L226
\[5]: https://github.com/mmtk/mmtk-core/blob/4851e7ac7e8a7bd70ce65935c4ac1ff430cab6f1/src/vm/collection.rs#L66-L73
\[6]: https://github.com/mmtk/mmtk-openjdk/blob/master/openjdk/mmtkHeap.cpp#L508
\[7]: https://github.com/mmtk/mmtk-core/blob/4851e7ac7e8a7bd70ce65935c4ac1ff430cab6f1/src/util/alloc/allocator.rs#L35

#### Solutions?
One proposed solution could be to force the VM to throw the error and print the stack trace, similar to how `vm_exit_during_initialization()` [8] does. This will not violate MMTk's contract, but does not leverage the current OOM mechanism in OpenJDK and is also not the expected way to throw an OOM error.

Another solution could be to audit and refactor all places where MMTk assumes that we don't return a `null` pointer to the VM. This includes allocation, object metadata initialization, etc.

\[8]: https://github.com/mmtk/openjdk/blob/jdk-11.0.11+6-mmtk/src/hotspot/share/runtime/java.cpp#L632-L647

**Comment by k-sareen** [comment]
In a meeting, @qinsoon has mentioned that MMTk's contract is too strong and it would be best to relax its expectations in order to support Java correctly by returning `null` to the VM and letting the Java threads throw the OOM error.
